app/routes/user.py
from flask import Blueprint, render_template, url_for, redirect, request
from flask_login import current_user, logout_user, login_user

from ..context import provider_manager, login_manager, db
from ..models.user import User


route_user_bp = Blueprint("user", __name__)


@login_manager.user_loader
def user_loader(user_id):
    return db.session.get(User, int(user_id))


@route_user_bp.route("/authorize/<provider>")
def route_oauth2_authorize(provider):
    if not current_user.is_anonymous:
        return redirect(url_for("main_bp.main.route_index"))

    try:
        response = provider_manager.authorize(provider)
    except ValueError as e:
        return str(e), 400

    return response


@route_user_bp.route("/auth_callback/<provider>")
def route_oauth2_callback(provider):
    if not current_user.is_anonymous:
        return redirect(url_for("main.route_index"))

    try:
        response_data = provider_manager.oauth_callback(request, provider)
    except ValueError as e:
        return str(e), 400

    if not response_data:
        return "No data received from the OAuth provider", 400

    user = db.session.scalar(
        db.select(User).where(User.email == response_data.get("email"))
    )

    if not user:
        authorized_user = User(
            response_data.get("email"),
            provider,
            response_data.get("name", "Unknown User"),
            response_data.get("picture", None),
        )
    else:
        authorized_user = user
        authorized_user.name = response_data.get("name", user.name)
        authorized_user.picture = response_data.get("picture", user.picture)

    db.session.add(authorized_user)
    db.session.commit()

    login_user(authorized_user)
    return redirect(url_for("main.route_index"))


@route_user_bp.route("/logout", methods=["GET"])
def route_logout():
    if current_user.is_authenticated:
        logout_user()
        return render_template(
            "redirect.html",
            redirect_url=url_for("main.route_index"),
            message="You have been logged out.",
        )

    return render_template(
        "redirect.html",
        redirect_url=url_for("main.route_index"),
        message="You are not logged in.",
    )

app/routes/watch.py
import time
import uuid

from sqlalchemy import func
from flask import Blueprint, render_template, session, url_for, redirect
from flask_login import current_user

from ..context import db, storage_manager

from ..models.comment import Comment
from ..models.likes import Likes
from ..models.user import User
from ..models.video import Video
from ..models.views import Views

route_watch_bp = Blueprint("watch", __name__, url_prefix="/watch")


@route_watch_bp.route("/<video_hash>", methods=["GET"])
def route_watch(video_hash):
    video = db.session.scalar(db.select(Video).where(Video.hash == video_hash))

    if not video:
        return render_template(
            "redirect.html",
            redirect_url=url_for("main.route_index"),
            message="Video not found.",
            timeout=60,
        )

    video_stream_url = None

    try:
        video_stream_url = storage_manager.get_public_url(
            f"transcoded/{video.hash}/manifest.mpd"
        )

        if video.status != 0:
            video.status = 0
            video.thumbnail_url = storage_manager.get_public_url(
                f"transcoded/{video.hash}/small-thumbnail0000000000.jpeg"
            )

    except RuntimeError as e:
        if "does not exist in the bucket" in str(e) and video.status == 0:
            video.status = 1

    db.session.commit()

    video_info = {
        "video": video,
        "video_url": video_stream_url,
        "uploader": db.session.scalar(db.select(User).where(User.id == video.user_id)),
        "view_count": (
            db.session.execute(
                db.select(func.count(Views.id)).where(Views.video_id == video.id)
            ).scalar_one_or_none()
            or 0
        ),
        "like_count": (
            db.session.execute(
                db.select(func.count(Likes.id)).where(Likes.video_id == video.id)
            ).scalar_one_or_none()
            or 0
        ),
        # include user avatar per comment
        "comments": (
            db.session.execute(
                db.select(Comment, User.picture.label("user_picture"))
                .join(User, Comment.user_id == User.id)
                .where(Comment.video_id == video.id)
                .order_by(Comment.created_at.desc())
            ).all()
        ),
        "liked": (
            db.session.scalar(
                db.select(Likes).where(
                    Likes.video_id == video.id,
                    Likes.user_id == current_user.id
                    if current_user.is_authenticated
                    else None,
                )
            )
            is not None
        ),
    }

    watch_id = uuid.uuid4().hex

    if "watching_list" not in session:
        session["watching_list"] = {}

    watching_list = session["watching_list"]
    watching_list[watch_id] = {
        "video_hash": video.hash,
        "watch_start_ts": time.time(),
        "watched": False,
    }

    session["watching_list"] = watching_list

    return render_template(
        "watch.html", user=current_user, video_info=video_info, watch_id=watch_id
    )


@route_watch_bp.route("/waitfor/<video_hash>", methods=["GET"])
def route_waitfor(video_hash):
    video = db.session.scalar(db.select(Video).where(Video.hash == video_hash))

    if not video:
        return render_template(
            "redirect.html",
            redirect_url=url_for("main.route_index"),
            message="Video not found.",
            timeout=5,
        )

    if video.status == 0:
        return redirect(url_for("watch.route_watch", video_hash=video_hash))

    elif video.status in (1, 2):
        return render_template(
            "waitfor.html",
            user=current_user,
            video=video,
        )

    return render_template(
        "redirect.html",
        redirect_url=url_for("main.route_index"),
        message="Video processing failed.",
        timeout=5,
    )

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>{% block title %}{% endblock %} - PSEUDOTUBE</title>
		<link rel="stylesheet" href="{{ url_for('static', filename='common.css') }}">

		<!-- UI version of Shaka Player (includes shaka.ui) -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.3.5/controls.css">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/shaka-player/4.3.5/shaka-player.ui.js"></script>

		{% block head %}
		{% endblock %}
	</head>
	<body>
		<header class="top-bar">
			<a href="/" class="logo">PSEUDOTUBE</a>

			<div class="text-bar">
				<input id="search-bar-input" type="text" class="input-text" placeholder="Search...">
			</div>

			<div class="right-section">
				{% if user.is_authenticated %}

				{% include "upload_modal.html" %}

				<div class="account-btn-group">
					<p class="pill-button gray">
					<img src={{user.picture}} class="picture">
					</p>
					<a href="{{ url_for('user.route_logout') }}" class="pill-button black" title="Logout">⍈</a>
				</div>

				{% else %}
				<a href="{{ url_for('user.route_oauth2_authorize', provider='google') }}" class="btn red" title="Login">Login</a>
				{% endif %}
			</div>
		</header>

		{% block content %}{% endblock %}
		{% block scripts %}{% endblock %}

		<footer class="footer">
			<p>© PSEUDOTUBE</p>
			<a href="https://github.com/snpynk/pseudotube_flask_app" target="_blank" rel="noopener noreferrer">GitHub</a>
		</footer>

		<script>
			document.getElementById("search-bar-input")?.addEventListener('keypress', function (event) {
				if (event.key === 'Enter') {
					const query = this.value;
					if (query) {
						window.location.href = `/search?query=${encodeURIComponent(query)}`;
					}
				}
			});
		</script>
		{% if user.is_authenticated %}
		<script src="{{ url_for('static', filename='upload.js') }}"></script>
		{% endif %}
	</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<!-- Row 1 -->
<div class="section-row">
	<section class="section">
		<h2 class="section-title">Trending</h2>
		<div class="grid">
			{% if trending|length == 0 %}
				<p class="">No trending videos yet.</p>
			{% endif %}
			{% for video, views, user_picture in trending %}
			<div class="card">
				<a href="/watch/{{ video.hash }}" class="card-link">
					<div class="card-thumb" style="background-image: url('{{ video.thumbnail_url }}');"></div>
					<div class="card-header">
						<div class="card-title">
							<img src="{{user_picture}}" alt="Uploader avatar" class="video-card-avatar" />
							{{ video.title }}
						</div>
						<div class="card-metadata">{{ views }}</div>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</section>

	<section class="section">
		<h2 class="section-title">Most Liked</h2>
		<div class="grid">
			{% if most_liked|length == 0 %}
				<p class="">No videos liked yet.</p>
			{% endif %}
			{% for video, views, user_picture in most_liked %}
			<div class="card">
				<a href="/watch/{{ video.hash }}" class="card-link">
					<div class="card-thumb" style="background-image: url('{{ video.thumbnail_url }}');"></div>
					<div class="card-header">
						<div class="card-title">
							<img src="{{user_picture}}" alt="Uploader avatar" class="video-card-avatar" />
							{{ video.title }}
						</div>
						<div class="card-metadata">{{ views }}</div>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</section>
</div>

<div class="section-row">
	<section class="section">
		<h2 class="section-title">Most recent</h2>
		<div class="grid">
			{% if most_recent|length == 0 %}
				<p class="">No videos uploaded yet.</p>
			{% endif %}
			{% for video, views, user_picture in most_recent %}
			<div class="card">
				<a href="/watch/{{ video.hash }}" class="card-link">
					<div class="card-thumb" style="background-image: url('{{ video.thumbnail_url }}');"></div>
					<div class="card-header">
						<div class="card-title">
							<img src="{{user_picture}}" alt="Uploader avatar" class="video-card-avatar" />
							{{ video.title }}
						</div>
						<div class="card-metadata">{{ views }}</div>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</section>

	<section class="section">
		<h2 class="section-title">Most Watched</h2>
		<div class="grid">
			{% if most_watched|length == 0 %}
				<p class="">No videos have been watched yet.</p>
			{% endif %}
			{% for video, views, user_picture in most_watched %}
			<div class="card">
				<a href="/watch/{{ video.hash }}" class="card-link">
					<div class="card-thumb" style="background-image: url('{{ video.thumbnail_url }}');"></div>
					<div class="card-header">
						<div class="card-title">
							<img src="{{user_picture}}" alt="Uploader avatar" class="video-card-avatar" />
							{{ video.title }}
						</div>
						<div class="card-metadata">{{ views }}</div>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</section>
</div>

<div class="section-row">
	<section class="section">
		<h2 class="section-title">Random</h2>
		<div class="grid">
			{% if random_videos|length == 0 %}
				<p class="">No random videos yet.</p>
			{% endif %}
			{% for video, views, user_picture in random_videos %}
			<div class="card">
				<a href="/watch/{{ video.hash }}" class="card-link">
					<div class="card-thumb" style="background-image: url('{{ video.thumbnail_url }}');"></div>
					<div class="card-header">
						<div class="card-title">
							<img src="{{user_picture}}" alt="Uploader avatar" class="video-card-avatar" />
							{{ video.title }}
						</div>
						<div class="card-metadata">{{ views }}</div>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</section>
	<section class="section">
		<h2 class="section-title">Your Videos</h2>
		<div class="grid">
			{% if user_videos|length == 0 %}
				<p class="">You have not uploaded any videos yet.</p>
			{% endif %}
			{% for video, views, user_picture in user_videos %}
			<div class="card">
				<a href="/watch/{{ video.hash }}" class="card-link">
					<div class="card-thumb" style="background-image: url('{{ video.thumbnail_url }}');"></div>
					<div class="card-header">
						<div class="card-title">
							<img src="{{user_picture}}" alt="Uploader avatar" class="video-card-avatar" />
							{{ video.title }}
						</div>
						<div class="card-metadata">{{ views }}</div>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</section>
</div>
{% endblock %}

templates/redirect.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>PSEUDOTUBE</title>
	</head>
	<link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='common.css') }}">
	<body>
		<!-- Redirect Section -->
		<div class="section">
			<h2>{{ message }}</h2>
			<p id="countdown-pg">You will be redirected {{ timeout | default(3) }} seconds. If not, click <a href="{{ redirect_url }}">here</a>.</p>
		</div>
		<script>
		// Countdown to redirect
		var countdown = document.getElementById("countdown-pg");
		var seconds = {{ timeout | default(3) }};

		var interval = setInterval(function() {
			if (seconds > 0) {
				console.log(countdown.innerHTML);
				countdown.innerHTML = countdown.innerHTML.replace(/(\d+)/, seconds);
				seconds--;
			} else {
				clearInterval(interval);
				window.location.href = "{{ redirect_url }}";
			}
		}, 1000);
		</script>
	</body>
</html>

templates/search_results.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<!-- Row 1 -->
<div class="section-row">
	<section class="section">
		<div class="stack">
			{% if videos|length == 0 %}
			<div class="card">
				<p class="card-title">No videos found.</p>
			</div>
			{% endif %}
			{% for video, views, user_picture in videos %}
			<div class="card">
				<a href="/watch/{{ video.hash }}" class="card-link">
					<div class="card-thumb" style="background-image: url('{{ video.thumbnail_uri }}');"></div>
					<div class="card-header">
						<div class="card-title">
							<img src="{{user_picture}}" alt="Uploader avatar" class="video-card-avatar" />
							{{ video.title }}
						</div>
						<div class="card-metadata">{{ views }}</div>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</section>
</div>
{% endblock %}

templates/upload_modal.html
{% if user.is_authenticated %}
<!-- Upload Button -->
<button id="upload-button" class="btn red">Upload</button>

<!-- Upload Modal -->
<div class="modal-overlay">
	<button id="upload-modal-close-button" class="btn gray modal-close">&times;</button>

	<div class="modal">
		<h2 class="modal-title">Upload File</h2>
		<p class="modal-description">Please choose a file to upload. You can also drag and drop it below.</p>

		<form class="upload-form" id="upload-form" action="" method="post" enctype="multipart/form-data">
			<div class="form-group">
				<label for="video-title">Title</label>
				<input type="text" id="video-title" name="video-title" class="input-text" required>
			</div>

			<div class="form-group">
				<label for="video-desc">Description</label>
				<textarea id="video-desc" name="video-desc" class="textarea" rows="4"></textarea>
			</div>

			<label for="file-upload" class="upload-area" id="upload-area">
				<input type="file" id="file-upload" name="file-upload" hidden required />
				<span id="upload-text">Click or drag file here to upload</span>
			</label>

			<progress id="upload-progress" value="0" max="100" style="width: 100%; display: none;"></progress>
			<p id="upload-status" style="font-size: 14px; color: #555;"></p>

			<button id="upload-submit" type="submit" class="btn red">Submit</button>
		</form>
	</div>
</div>
{% endif %}

templates/waitfor.html
{% extends "base.html" %}
{% block title %}{{ video.title }}{% endblock %}
{% block content %}

<div class="watch-container">
	<div class="video-player">
		<div class="video-placeholder-message">
			<h2 id="message"></h2>
		</div>
	</div>

	<div class="title-like-row">
		<div style="flex:1; min-width: 0;">
			<div class="video-title">{{ video.title }}</div>
		</div>
	</div>

	{% if video.description != None %}
	<div class="video-description">{{ video.description }}</div>
	{% endif %}

</div>
{% endblock %}

{% block scripts %}

<script>
let mainInterval;
function redirectTo(url, message, delay) {
	timeLeft = delay;

	setInterval(() => {
		document.getElementById('message').innerText = message.replace('%d', timeLeft);
		timeLeft--;

		if (timeLeft < 0) {
			window.location.href = url;
		}
	}, 1000);
}
document.addEventListener('DOMContentLoaded', function() {
	// Placeholder for any JavaScript functionality needed
	let retry = 0;
	const mainInterval = setInterval(function() {
		// Simulate video processing completion
		fetch("/api/transcoder/status?video_hash={{ video.hash }}")
			.then(response => response.json())
			.then(data => {
				if (data.status === 'processing' || data.status === 'preparing') {
					random_emoji = ['🔄', '⏳', '⌛', '🕒'][Math.floor(Math.random() * 4)];
					retry++;
					document.getElementById('message').innerText = `PSEUDOTUBE is ${data.status} your video... ${random_emoji}`;
				} else {
					if (data.status === 'processed') {
						redirectTo("/watch/{{video.hash}}", "Video processed! Redirecting in %d seconds...", 3);
					} else if (data.status === 'failed') {
						redirectTo("/watch/{{video.hash}}", "Video processing failed and the video will be deleted. Redirecting to home in %d seconds...", 3);
					} else {
						document.getElementById('message').innerText = "Unknown status: " + data.status;
					}
					clearInterval(mainInterval); // Stop checking once processing is done
				}
			})
			.catch(error => console.error('Error fetching video:', error));
	}, 1000); 
});

</script>

{% endblock %}

templates/watch.html
{% extends "base.html" %}
{% block title %}{{ video_info.video.title }}{% endblock %}
{% block content %}

<div class="page-container">
	<div class="video-player-section">
		<div class="video-frame">
			{% if video_info.video.status > 0 and video_info.video.status < 3 %}
			<div class="video-placeholder-message">
				<h2 class="video-error">This video is still processing.</h2>
			</div>
			{% elif video_info.video.status == 3 %}
			<div class="video-placeholder-message">
				<h2 class="video-error">This video has been been marked as malformed.</h2>
			</div>
			{% else %}
			<div id="video-container" class="shaka-video-container">
				<video id="video-player" autoplay="false" data-url={{ video_info.video_url }} data-hash={{ video_info.video.hash }} data-watchid={{ watch_id }} data-liked={{ video_info.liked }}></video>
			</div>
			{% endif %}
		</div>
	</div>

	<div class="video-info-section">
		<div class="title-like-row">
			<div class="uploader-info">
				<img src="{{ video_info.uploader.picture }}" class="uploader-avatar" />
			</div>
			<div style="flex:1; min-width: 0;">
				<div class="video-title">{{ video_info.video.title }}</div>
				<div class="video-stats">
					{{ video_info.view_count }} views • {{ video_info.video.created_at.strftime('%b %d, %Y') }}
				</div>
			</div>
			{% if user.id == video_info.video.user_id %}
			<button id="delete-button" class="delete-button" aria-label="Delete video" >🗑️</button>

			{% endif %}
			<button id="like-button" class="like-button" aria-label="Like video" {% if video_info.liked %}liked{% endif %}>
				♡  <span id="like-count">{{ video_info.like_count }}</span>
			</button>
		</div>	

		{% if video_info.video.description != None %}
		<div class="video-description">{{ video_info.video.description }}</div>
		{% endif %}
	</div>

	<div class="comments-section">
		<form id="comment-form" class="comment-form" method="POST" action="/watch/{{ video_info.video.hash }}#comments">
			<textarea id="comment-text-input" name="comment_text" class="comment-input" rows="3" placeholder="Add a comment..."></textarea>
			<button type="submit" class="comment-submit-btn">Submit</button>
		</form>

		<div id="comments" class="comments-section">
			{% for comment in video_info.comments %}
			<div class="comment">
				<img src="{{ comment.user_picture }}" alt="Commenter avatar" class="comment-avatar" />
				<div class="comment-content">
					<div class="comment-meta">{{ comment[0].created_at.strftime('%b %d, %Y') }}</div>
					<div class="comment-text">{{ comment[0].text }}</div>
				</div>
			</div>
			{% else %}
			<p>No comments yet. Be the first to comment!</p>
			{% endfor %}
		</div>
	</div>

</div>
{% endblock %}

{% block scripts %}

<script src={{ url_for('static', filename='watch.js') }}></script>

{% endblock %}